# Default values for caddy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/jenkinsxio/caddy
  tag: 0.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

services:
  - type: ClusterIP
    name: http
    port: 8080
    targetPort: 8080
  - type: ClusterIP
    name: prometheus
    port: 9180
    targetPort: 9180

persistence:
  enabled: true
  size: 4Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}
