{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $fullName := include "caddy.name" . -}}
{{- $chart := include "caddy.chart" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    helm.sh/chart: {{ $chart }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ $fullName }}
    release: {{ $releaseName }}
